// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hackme.Models;

namespace hackme.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181010151632_Login")]
    partial class Login
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("hackme.Models.Login", b =>
                {
                    b.Property<string>("Password")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Password");

                    b.ToTable("Logins");

                    b.HasData(
                        new { Password = "e6895616-4b86-4be3-9450-26fbb8a0f605" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
